version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
  achat-backend:
    image: yosrakaroui98/achat
    container_name: achatcontainer
    restart: on-failure
    ports:
      - "9091:9091"
    depends_on:
      - mysqldb
  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    # other configurations for prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  

  