version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=0000
      - MYSQL_DATABASE=achatdb
    ports:
      - "3306:3306"
    volumes:
      - /home/mysql/data:/var/lib/mysql
  achat-backend:
    depends_on:
      - mysqldb
    image:  skanderbrahim/achat:1.0.0
    container_name: achatcontainer
    restart: on-failure
    ports:
      - "8082:8082"
    environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : "0000",
        "spring.datasource.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.datasource.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true