version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - /home/mysql/data:/var/lib/mysql
  achat-backend:
    image: yosrakaroui98/achat
    container_name: achatcontainer
    restart: on-failure
    ports:
      - "9091:9091"
    depends_on:
      - mysqldb
