version: "3.8"

services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=mysqldb

    ports:
      - 3306:3306
    volumes:
      - /home/mysql/data:/var/lib/mysql
  app-achat:
    depends_on:
      - mysqldb
    image: ayedsara/achat-1.0
    restart: on-failure
    ports:
      - 8082:8082