version: '3.8'
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - /home/mysql/data:/var/lib/mysql
  achat-backend:
    image:  medalirommene/achat:1.0.0
    container_name: achatcontainer
    restart: on-failure
    ports:
      - "8082:8082"
    depends_on:
      - mysqldb